### ISSUE TITLE
Nothing happens when I run .bat

### ISSUE THREAD

**Issue by goldenfalcon** [ToxicFrog/bltool#12]
I edited the info for steam ID, BL name and password. Just brings up a blank notepad.

I added - SET PATH=%PATH%;"C:\apps\Java\jre7\bin;C:\apps\Java\jre6\bin" - because I think that's where my java is installed. This was added above - SET PATH=%PATH%;"C:\Program Files\Java\jre7\bin;C:\Program Files\Java\jre6\bin" - so now there are 3 lines there now. Still just a blank notepad.

**Comment by alucardbc** [comment]
I'm running into what appears to be the same problem. However looking at the output from Windows Command Prompt it is errors out with: "Error: Unable to access jarfile bltool.jar" It does this just before opening the games.txt file and after the notepad is closed. Looking at the directory and the github files, that jar file is just flat out missing. Was this file accidentally forgotten on push?

**Comment by ToxicFrog** [comment]
The jar is there:

    $ unzip -l bltool-0.2.1.zip \*.jar
     16051636  2015-02-10 10:10   bltool-0.2.1/bltool.jar

Make sure that you downloaded the [latest release](https://github.com/toxicfrog/bltool/releases/) and not the source code; the latter is for developers and doesn't come with the jar.
