### ISSUE TITLE
Getting error: "Unable to access jarfile bltool.jar" (What am i doing wrong?)

### ISSUE THREAD

**Issue by jacobmix** [ToxicFrog/bltool#19]
Keep getting this error: "Error: Unable to access jarfile bltool.jar"
What am i doing wrong?

My Steam2Backloggery, and CMD output (With password replaced with *'s):

steam2backloggery.bat file:

>REM =====================
REM USER SETTINGS GO HERE
REM =====================

>set STEAM_NAME=jacobmix
set BL_NAME=backloggery jacobmix
set BL_PASS=backloggery **********
set EDITOR=notepad

>REM =========================================
REM NO USER SERVICEABLE PARTS BELOW THIS LINE
REM =========================================

>REM Java on windows is a complete nightmare, and doesn't always properly get
REM added to %PATH%. So we add a bunch of plausible directories here.

>SET PATH=%PATH%;"D:\Java\jdk1.8.0_31\bin"

>java -jar bltool.jar --steam-name "%STEAM_NAME%" --bl-name "%BL_NAME%" --bl-pass "%BL_PASS%" --filter-from backloggery --from steam --to text --output games.txt
%EDITOR% games.txt
java -jar bltool.jar --bl-name "%BL_NAME%" --bl-pass "%BL_PASS%" --from text --to backloggery --input games.txt

CMD output:

>C:\Windows\system32>cd /D "D:\bltool-master"

>D:\bltool-master>steam2backloggery.bat

>D:\bltool-master>REM =====================

>D:\bltool-master>REM USER SETTINGS GO HERE

>D:\bltool-master>REM =====================

>D:\bltool-master>set STEAM_NAME=jacobmix

>D:\bltool-master>set BL_NAME=backloggery jacobmix

>D:\bltool-master>set BL_PASS=backloggery **********

>D:\bltool-master>set EDITOR=notepad

>D:\bltool-master>REM =========================================

>D:\bltool-master>REM NO USER SERVICEABLE PARTS BELOW THIS LINE

>D:\bltool-master>REM =========================================

>D:\bltool-master>REM Java on windows is a complete nightmare, and doesn't always
 properly get

>D:\bltool-master>REM added to C:\Program Files\Common Files\Microsoft Shared\Win
dows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\P
rogram Files (x86)\Python27\;C:\ProgramData\Oracle\Java\javapath;C:\Program File
s (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system
32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.
0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program F
iles\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Inte
l\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R
) Management Engine Components\IPT;C:\Program Files (x86)\AMD\ATI.ACE\Core-Stati
c;C:\Program Files\Calibre2\;C:\Program Files (x86)\Livestreamer;C:\Program File
s (x86)\Windows Live\Shared;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Comm
on;C:\Program Files (x86)\Skype\Phone\. So we add a bunch of plausible directori
es here.

>D:\bltool-master>SET PATH=C:\Program Files\Common Files\Microsoft Shared\Windows
 Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Progr
am Files (x86)\Python27\;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x
86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C
:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C
:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files
\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\In
tel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Ma
nagement Engine Components\IPT;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:
\Program Files\Calibre2\;C:\Program Files (x86)\Livestreamer;C:\Program Files (x
86)\Windows Live\Shared;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C
:\Program Files (x86)\Skype\Phone\;"D:\Java\jdk1.8.0_31\bin"

>D:\bltool-master>java -jar bltool.jar --steam-name "jacobmix" --bl-name "backlog
gery jacobmix" --bl-pass "backloggery **********" --filter-from backloggery --from
 steam --to text --output games.txt
Error: Unable to access jarfile bltool.jar

>D:\bltool-master>notepad games.txt

>D:\bltool-master>java -jar bltool.jar --bl-name "backloggery jacobmix" --bl-pass
 "backloggery **********" --from text --to backloggery --input games.txt
Error: Unable to access jarfile bltool.jar

Here's my DxDiag txt file if it's gonna help: http://pastebin.com/XRQb7DH7
I've already set some environment variables before. If that might be a problem.
Some can be seen here: http://prntscr.com/7twyp0
Also can't find a actual bltool.jar file anywhere.

**Comment by ToxicFrog** [comment]
On July 17, 2015 4:52:29 PM EDT, jacobmix <notifications@github.com> wrote:
>Keep getting this error: "Error: Unable to access jarfile bltool.jar"
>What am i doing wrong?
>
>My Steam2Backloggery, and CMD output (With password replaced with *'s):
>>steam2backloggery.bat file:
>
>>REM =====================
>REM USER SETTINGS GO HERE
>REM =====================
>
>>set STEAM_NAME=jacobmix
>set BL_NAME=backloggery jacobmix
>set BL_PASS=backloggery **********
>set EDITOR=notepad
>
>>REM =========================================
>REM NO USER SERVICEABLE PARTS BELOW THIS LINE
>REM =========================================
>
>>REM Java on windows is a complete nightmare, and doesn't always
>properly get
>REM added to %PATH%. So we add a bunch of plausible directories here.
>
>>SET PATH=%PATH%;"D:\Java\jdk1.8.0_31\bin"
>
>>java -jar bltool.jar --steam-name "%STEAM_NAME%" --bl-name "%BL_NAME%"
>--bl-pass "%BL_PASS%" --filter-from backloggery --from steam --to text
>--output games.txt
>%EDITOR% games.txt
>java -jar bltool.jar --bl-name "%BL_NAME%" --bl-pass "%BL_PASS%" --from
>text --to backloggery --input games.txt
>
>
>
>>CMD output:
>
>>C:\Windows\system32>cd /D "D:\bltool-master"
>
>>D:\bltool-master>steam2backloggery.bat
>
>>D:\bltool-master>REM =====================
>
>>D:\bltool-master>REM USER SETTINGS GO HERE
>
>>D:\bltool-master>REM =====================
>
>>D:\bltool-master>set STEAM_NAME=jacobmix
>
>>D:\bltool-master>set BL_NAME=backloggery jacobmix
>
>>D:\bltool-master>set BL_PASS=backloggery **********
>
>>D:\bltool-master>set EDITOR=notepad
>
>>D:\bltool-master>REM =========================================
>
>>D:\bltool-master>REM NO USER SERVICEABLE PARTS BELOW THIS LINE
>
>>D:\bltool-master>REM =========================================
>
>>D:\bltool-master>REM Java on windows is a complete nightmare, and
>doesn't always
> properly get
>
>>D:\bltool-master>REM added to C:\Program Files\Common Files\Microsoft
>Shared\Win
>dows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows
>Live;C:\P
>rogram Files
>(x86)\Python27\;C:\ProgramData\Oracle\Java\javapath;C:\Program File
>s (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS
>Client\;C:\Windows\system
>32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.
>0\;C:\Program Files\Intel\Intel(R) Management Engine
>Components\DAL;C:\Program F
>iles\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files
>(x86)\Inte
>l\Intel(R) Management Engine Components\DAL;C:\Program Files
>(x86)\Intel\Intel(R
>) Management Engine Components\IPT;C:\Program Files
>(x86)\AMD\ATI.ACE\Core-Stati
>c;C:\Program Files\Calibre2\;C:\Program Files
>(x86)\Livestreamer;C:\Program File
>s (x86)\Windows Live\Shared;C:\Program Files (x86)\NVIDIA
>Corporation\PhysX\Comm
>on;C:\Program Files (x86)\Skype\Phone\. So we add a bunch of plausible
>directori
>es here.
>
>>D:\bltool-master>SET PATH=C:\Program Files\Common Files\Microsoft
>Shared\Windows
>Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows
>Live;C:\Progr
>am Files (x86)\Python27\;C:\ProgramData\Oracle\Java\javapath;C:\Program
>Files (x
>86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS
>Client\;C:\Windows\system32;C
>:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C
>:\Program Files\Intel\Intel(R) Management Engine
>Components\DAL;C:\Program Files
>\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files
>(x86)\Intel\In
>tel(R) Management Engine Components\DAL;C:\Program Files
>(x86)\Intel\Intel(R) Ma
>nagement Engine Components\IPT;C:\Program Files
>(x86)\AMD\ATI.ACE\Core-Static;C:
>\Program Files\Calibre2\;C:\Program Files (x86)\Livestreamer;C:\Program
>Files (x
>86)\Windows Live\Shared;C:\Program Files (x86)\NVIDIA
>Corporation\PhysX\Common;C
>:\Program Files (x86)\Skype\Phone\;"D:\Java\jdk1.8.0_31\bin"
>
>>D:\bltool-master>java -jar bltool.jar --steam-name "jacobmix"
>--bl-name "backlog
>gery jacobmix" --bl-pass "backloggery **********" --filter-from
>backloggery --from
> steam --to text --output games.txt
>Error: Unable to access jarfile bltool.jar
>
>>D:\bltool-master>notepad games.txt
>
>>D:\bltool-master>java -jar bltool.jar --bl-name "backloggery jacobmix"
>--bl-pass
>"backloggery **********" --from text --to backloggery --input games.txt
>Error: Unable to access jarfile bltool.jar
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/ToxicFrog/bltool/issues/19

It looks like you downloaded the source code, which is only of interest to developers and does not come with the jar. Unless you want to build the jar yourself, you should instead use the latest release: https://github.com/ToxicFrog/bltool/releases
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jacobmix** [comment]
Thank you. Since i couldn't find a download link or anything in the "README.md"
I just pressed the "Download as ZIP"  button expected to get the latest release.
