### ISSUE TITLE
JSON output?

### ISSUE THREAD

**Issue by SangSatori** [ToxicFrog/bltool#23]
JSON is kind of a _lingua franca_ for data storage and serialization - I think it would greatly increase the interoperability with software written in other languages and make it easier to parse in languages with no good support for parsing EDN. Could it be possible to implement this?

**Comment by ToxicFrog** [comment]
It wouldn't be at all difficult to add. I'm really short on time lately, but if I have a spare hour I'll see about it. Clojure has decent JSON support, IIRC. You can do a bunch of things with EDN that JSON doesn't support, but I don't think bltool actually uses those features.

**Comment by ToxicFrog** [comment]
Added in release 0.2.2.
