### ISSUE TITLE
Unable to log in to Backloggery

### ISSUE THREAD

**Issue by GotSka81** [ToxicFrog/bltool#27]
When attempted to run a custom command or using the pre-built batch file, attempts to log into Backloggery fail.  After the return "Logging into Backloggery as X" the error "Unable to log in to Backloggery. Please check your username and password" is shown.  I quadruple-checked and made sure that the correct login info is set in the designated variables and confirmed that my account is not locked.  

I don't know if you're using an API or a webscraper, but perhaps Backloggery changed something and now the login functionality is broken?  I know this is sort of an abandoned project at this point (no offense or disrespect intended, I loved BLTool when I could get it to work!).
![backloggery](https://user-images.githubusercontent.com/32017180/30513030-53161ec0-9aca-11e7-92bf-41f2d9f645d4.png)

**Comment by ToxicFrog** [comment]
I'll take a look. It uses a web scraper because backloggery doesn't have an API, so it's kind of fragile.

**Comment by ToxicFrog** [comment]
Fixed -- when I wrote this backloggery didn't support https login. Now it not only supports it, it requires it, so the old http login was failing. v0.2.3 should work.

**Comment by GotSka81** [comment]
Thanks!  I'm glad it was a relatively simple fix, and https use is always good.
