### ISSUE TITLE
Writing to Backloggery Failing

### ISSUE THREAD

**Issue by GotSka81** [ToxicFrog/bltool#28]
Hello again!

I know I just pointed out the authentication issue and I apologize for being a thorn in your side, but it looks like the import is failing as well.  Perhaps it's similar to the authentication issue or a change in formatting for the webscraper (https usage where http used to be)?  I don't intend to put work on your plate or appear to be demanding a fix, I just found the bug and thought I should report it.

![import](https://user-images.githubusercontent.com/32017180/30522353-b3236426-9b9c-11e7-830e-2726aca41dc9.png)

**Comment by ToxicFrog** [comment]
No worries, I appreciate bug reports. :)

You were right, it just wants HTTPS everywhere. Should be fixed in v0.2.4.

**Comment by GotSka81** [comment]
Once again, many thanks!
